// Generated by gencpp from file robot_drive/RechargeStatus.msg
// DO NOT EDIT!


#ifndef ROBOT_DRIVE_MESSAGE_RECHARGESTATUS_H
#define ROBOT_DRIVE_MESSAGE_RECHARGESTATUS_H

#include <ros/service_traits.h>


#include <robot_drive/RechargeStatusRequest.h>
#include <robot_drive/RechargeStatusResponse.h>


namespace robot_drive
{

struct RechargeStatus
{

typedef RechargeStatusRequest Request;
typedef RechargeStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RechargeStatus
} // namespace robot_drive


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_drive::RechargeStatus > {
  static const char* value()
  {
    return "1f8df5c7160361bad653e42bd128971e";
  }

  static const char* value(const ::robot_drive::RechargeStatus&) { return value(); }
};

template<>
struct DataType< ::robot_drive::RechargeStatus > {
  static const char* value()
  {
    return "robot_drive/RechargeStatus";
  }

  static const char* value(const ::robot_drive::RechargeStatus&) { return value(); }
};


// service_traits::MD5Sum< ::robot_drive::RechargeStatusRequest> should match
// service_traits::MD5Sum< ::robot_drive::RechargeStatus >
template<>
struct MD5Sum< ::robot_drive::RechargeStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_drive::RechargeStatus >::value();
  }
  static const char* value(const ::robot_drive::RechargeStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_drive::RechargeStatusRequest> should match
// service_traits::DataType< ::robot_drive::RechargeStatus >
template<>
struct DataType< ::robot_drive::RechargeStatusRequest>
{
  static const char* value()
  {
    return DataType< ::robot_drive::RechargeStatus >::value();
  }
  static const char* value(const ::robot_drive::RechargeStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_drive::RechargeStatusResponse> should match
// service_traits::MD5Sum< ::robot_drive::RechargeStatus >
template<>
struct MD5Sum< ::robot_drive::RechargeStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_drive::RechargeStatus >::value();
  }
  static const char* value(const ::robot_drive::RechargeStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_drive::RechargeStatusResponse> should match
// service_traits::DataType< ::robot_drive::RechargeStatus >
template<>
struct DataType< ::robot_drive::RechargeStatusResponse>
{
  static const char* value()
  {
    return DataType< ::robot_drive::RechargeStatus >::value();
  }
  static const char* value(const ::robot_drive::RechargeStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_DRIVE_MESSAGE_RECHARGESTATUS_H
