// Generated by gencpp from file robot_drive/RechargeStatusResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_DRIVE_MESSAGE_RECHARGESTATUSRESPONSE_H
#define ROBOT_DRIVE_MESSAGE_RECHARGESTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int8.h>

namespace robot_drive
{
template <class ContainerAllocator>
struct RechargeStatusResponse_
{
  typedef RechargeStatusResponse_<ContainerAllocator> Type;

  RechargeStatusResponse_()
    : rechargeStatus()  {
    }
  RechargeStatusResponse_(const ContainerAllocator& _alloc)
    : rechargeStatus(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int8_<ContainerAllocator>  _rechargeStatus_type;
  _rechargeStatus_type rechargeStatus;





  typedef boost::shared_ptr< ::robot_drive::RechargeStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_drive::RechargeStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RechargeStatusResponse_

typedef ::robot_drive::RechargeStatusResponse_<std::allocator<void> > RechargeStatusResponse;

typedef boost::shared_ptr< ::robot_drive::RechargeStatusResponse > RechargeStatusResponsePtr;
typedef boost::shared_ptr< ::robot_drive::RechargeStatusResponse const> RechargeStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_drive::RechargeStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_drive::RechargeStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_drive::RechargeStatusResponse_<ContainerAllocator1> & lhs, const ::robot_drive::RechargeStatusResponse_<ContainerAllocator2> & rhs)
{
  return lhs.rechargeStatus == rhs.rechargeStatus;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_drive::RechargeStatusResponse_<ContainerAllocator1> & lhs, const ::robot_drive::RechargeStatusResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_drive

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_drive::RechargeStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_drive::RechargeStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_drive::RechargeStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_drive::RechargeStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_drive::RechargeStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_drive::RechargeStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_drive::RechargeStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f8df5c7160361bad653e42bd128971e";
  }

  static const char* value(const ::robot_drive::RechargeStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f8df5c7160361baULL;
  static const uint64_t static_value2 = 0xd653e42bd128971eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_drive::RechargeStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_drive/RechargeStatusResponse";
  }

  static const char* value(const ::robot_drive::RechargeStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_drive::RechargeStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int8 rechargeStatus\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int8\n"
"int8 data\n"
;
  }

  static const char* value(const ::robot_drive::RechargeStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_drive::RechargeStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rechargeStatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RechargeStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_drive::RechargeStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_drive::RechargeStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "rechargeStatus: ";
    s << std::endl;
    Printer< ::std_msgs::Int8_<ContainerAllocator> >::stream(s, indent + "  ", v.rechargeStatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_DRIVE_MESSAGE_RECHARGESTATUSRESPONSE_H
