// Generated by gencpp from file robot_drive/StopStatusResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_DRIVE_MESSAGE_STOPSTATUSRESPONSE_H
#define ROBOT_DRIVE_MESSAGE_STOPSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int8.h>

namespace robot_drive
{
template <class ContainerAllocator>
struct StopStatusResponse_
{
  typedef StopStatusResponse_<ContainerAllocator> Type;

  StopStatusResponse_()
    : stopStatus()  {
    }
  StopStatusResponse_(const ContainerAllocator& _alloc)
    : stopStatus(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int8_<ContainerAllocator>  _stopStatus_type;
  _stopStatus_type stopStatus;





  typedef boost::shared_ptr< ::robot_drive::StopStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_drive::StopStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StopStatusResponse_

typedef ::robot_drive::StopStatusResponse_<std::allocator<void> > StopStatusResponse;

typedef boost::shared_ptr< ::robot_drive::StopStatusResponse > StopStatusResponsePtr;
typedef boost::shared_ptr< ::robot_drive::StopStatusResponse const> StopStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_drive::StopStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_drive::StopStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_drive::StopStatusResponse_<ContainerAllocator1> & lhs, const ::robot_drive::StopStatusResponse_<ContainerAllocator2> & rhs)
{
  return lhs.stopStatus == rhs.stopStatus;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_drive::StopStatusResponse_<ContainerAllocator1> & lhs, const ::robot_drive::StopStatusResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_drive

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_drive::StopStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_drive::StopStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_drive::StopStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_drive::StopStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_drive::StopStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_drive::StopStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_drive::StopStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89132d6351c3e4fdaed584469dcb3e79";
  }

  static const char* value(const ::robot_drive::StopStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89132d6351c3e4fdULL;
  static const uint64_t static_value2 = 0xaed584469dcb3e79ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_drive::StopStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_drive/StopStatusResponse";
  }

  static const char* value(const ::robot_drive::StopStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_drive::StopStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int8 stopStatus\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int8\n"
"int8 data\n"
;
  }

  static const char* value(const ::robot_drive::StopStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_drive::StopStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stopStatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_drive::StopStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_drive::StopStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "stopStatus: ";
    s << std::endl;
    Printer< ::std_msgs::Int8_<ContainerAllocator> >::stream(s, indent + "  ", v.stopStatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_DRIVE_MESSAGE_STOPSTATUSRESPONSE_H
