// Generated by gencpp from file robot_drive/StopStatus.msg
// DO NOT EDIT!


#ifndef ROBOT_DRIVE_MESSAGE_STOPSTATUS_H
#define ROBOT_DRIVE_MESSAGE_STOPSTATUS_H

#include <ros/service_traits.h>


#include <robot_drive/StopStatusRequest.h>
#include <robot_drive/StopStatusResponse.h>


namespace robot_drive
{

struct StopStatus
{

typedef StopStatusRequest Request;
typedef StopStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopStatus
} // namespace robot_drive


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_drive::StopStatus > {
  static const char* value()
  {
    return "89132d6351c3e4fdaed584469dcb3e79";
  }

  static const char* value(const ::robot_drive::StopStatus&) { return value(); }
};

template<>
struct DataType< ::robot_drive::StopStatus > {
  static const char* value()
  {
    return "robot_drive/StopStatus";
  }

  static const char* value(const ::robot_drive::StopStatus&) { return value(); }
};


// service_traits::MD5Sum< ::robot_drive::StopStatusRequest> should match
// service_traits::MD5Sum< ::robot_drive::StopStatus >
template<>
struct MD5Sum< ::robot_drive::StopStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_drive::StopStatus >::value();
  }
  static const char* value(const ::robot_drive::StopStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_drive::StopStatusRequest> should match
// service_traits::DataType< ::robot_drive::StopStatus >
template<>
struct DataType< ::robot_drive::StopStatusRequest>
{
  static const char* value()
  {
    return DataType< ::robot_drive::StopStatus >::value();
  }
  static const char* value(const ::robot_drive::StopStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_drive::StopStatusResponse> should match
// service_traits::MD5Sum< ::robot_drive::StopStatus >
template<>
struct MD5Sum< ::robot_drive::StopStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_drive::StopStatus >::value();
  }
  static const char* value(const ::robot_drive::StopStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_drive::StopStatusResponse> should match
// service_traits::DataType< ::robot_drive::StopStatus >
template<>
struct DataType< ::robot_drive::StopStatusResponse>
{
  static const char* value()
  {
    return DataType< ::robot_drive::StopStatus >::value();
  }
  static const char* value(const ::robot_drive::StopStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_DRIVE_MESSAGE_STOPSTATUS_H
